export const eventsData = [
  {
    id: 1,
    date: "October 25, 2024",
    category: "education",
    title: "Celebration of World Anesthesia Day",
    tags: ["Health", "Medical"],
    description: "Celebration of World Anesthesia Day",
    image: "/assets/spotlights/cowad.webp",
    gallery: ["/assets/spotlights/cowad.webp"],
  },
  {
    id: 2,
    date: "October 10, 2024",
    category: "education",
    title: "Placement Drive - Hoping Minds",
    tags: ["Career", "Placement"],
    description: "Placement Drive - Hoping Minds",
    image: "/assets/spotlights/pdhm.webp",
    gallery: ["/assets/spotlights/pdhm.webp"],
  },
  {
    id: 3,
    date: "October 6, 2024",
    category: "education",
    title: "IGC students attended Google Development Fest",
    tags: ["Technology", "Development"],
    description: "IGC students attended Google Development Fest",
    image: "/assets/spotlights/isagdf.webp",
    gallery: ["/assets/spotlights/isagdf.webp"],
  },
  {
    id: 4,
    date: "September 26, 2024",
    category: "education",
    title: "Hospital visit - OTT students on 26th September 2024",
    tags: ["Healthcare", "Education"],
    description: "Hospital visit - OTT students on 26th September 2024",
    image: "/assets/spotlights/hvos.webp",
    gallery: ["/assets/spotlights/hvos.webp"],
  },
  {
    id: 5,
    date: "September 22, 2024",
    category: "education",
    title: "Operational Odyssey Launches at Indo Global Colleges",
    tags: ["Innovation", "Campus"],
    description: "Operational Odyssey Launches at Indo Global Colleges",
    image: "/assets/spotlights/oolaigc.webp",
    gallery: ["/assets/spotlights/oolaigc.webp"],
  },
  {
    id: 6,
    date: "September 17, 2024",
    category: "education",
    title: "AspireFox Placement Drive - 17th Sep 2024",
    tags: ["Career", "Placement"],
    description: "AspireFox Placement Drive - 17th Sep 2024",
    image: "/assets/spotlights/apd.webp",
    gallery: ["/assets/spotlights/apd.webp"],
  },
  {
    id: 7,
    date: "September 23, 2024",
    category: "education",
    title: "Hospital Visit for OTT students",
    tags: ["Healthcare", "Education"],
    description: "Hospital Visit for OTT students",
    image: "/assets/spotlights/hvfos.webp",
    gallery: ["/assets/spotlights/hvfos.webp"],
  },
  {
    id: 8,
    date: "September 18, 2024",
    category: "education",
    title: "Google Developer Groups on Campus",
    tags: ["Technology", "Development"],
    description: "Google Developer Groups on Campus",
    image: "/assets/spotlights/gdgoc.webp",
    gallery: ["/assets/spotlights/gdgoc.webp"],
  },
  {
    id: 9,
    date: "May 5, 2024",
    category: "education",
    title: "Teacher's Day Celebration 2024",
    tags: ["Celebration", "Education"],
    description: "Celebrating Teacher's Day with special events and honors",
    image: "/assets/spotlights/tdc.webp",
    gallery: ["/assets/spotlights/tdc.webp"],
  },
  {
    id: 10,
    date: "September 25, 2024",
    category: "education",
    title: "Talent Hunt Program Knack Seek - 2024",
    tags: ["Talent", "Recruitment"],
    description: "A program to identify and nurture talented students",
    image: "/assets/spotlights/thpks.webp",
    gallery: ["/assets/spotlights/thpks.webp"],
  },
  {
    id: 11,
    date: "July 15, 2024",
    category: "education",
    title: "Youth Skills Day",
    tags: ["Youth", "Skills"],
    description: "Youth Skills Day event focused on enhancing student skills",
    image: "/assets/spotlights/ch.webp",
    gallery: ["/assets/spotlights/ch.webp"],
  },
  {
    id: 12,
    date: "July 2, 2024",
    category: "education",
    title: "T20 World Cup Trophy",
    tags: ["Sports", "Celebration"],
    description: "Celebrating the T20 World Cup with a trophy ceremony",
    image: "/assets/spotlights/ph.webp",
    gallery: ["/assets/spotlights/ph.webp"],
  },
  {
    id: 13,
    date: "July 1, 2024",
    category: "education",
    title: "National Doctor's Day",
    tags: ["Healthcare", "Appreciation"],
    description: "Honoring doctors on National Doctor's Day",
    image: "/assets/spotlights/ndd.webp",
    gallery: ["/assets/spotlights/ndd.webp"],
  },
  {
    id: 14,
    date: "July 1, 2024",
    category: "education",
    title: "Empowering Educators",
    tags: ["Education", "Professional Development"],
    description: "Workshops and seminars to empower educators",
    image: "/assets/spotlights/ee.webp",
    gallery: ["/assets/spotlights/ee.webp"],
  },
  {
    id: 15,
    date: "June 23, 2024",
    category: "education",
    title: "Faculty Development Program",
    tags: ["Education", "Training"],
    description:
      "Enhancing faculty skills through targeted development programs",
    image: "/assets/spotlights/fdp.webp",
    gallery: ["/assets/spotlights/fdp.webp"],
  },
  {
    id: 16,
    date: "June 21, 2024",
    category: "education",
    title: "International Yoga Day",
    tags: ["Health", "Wellness"],
    description: "Celebrating International Yoga Day with various activities",
    image: "/assets/spotlights/iyd.webp",
    gallery: ["/assets/spotlights/iyd.webp"],
  },
  {
    id: 17,
    date: "June 17, 2024",
    category: "education",
    title: "EID AL-ADHA",
    tags: ["Cultural", "Religious"],
    description: "Celebrating EID AL-ADHA with community events",
    image: "/assets/spotlights/eaa.webp",
    gallery: ["/assets/spotlights/eaa.webp"],
  },
  {
    id: 18,
    date: "June 6, 2024",
    category: "education",
    title: "Tools Every Architect Student Should Know",
    tags: ["Architecture", "Technology"],
    description: "Introducing essential tools for architecture students",
    image: "/assets/spotlights/teassk.webp",
    gallery: ["/assets/spotlights/teassk.webp"],
  },
  {
    id: 19,
    date: "June 5, 2024",
    category: "education",
    title: "World Environment Day",
    tags: ["Environment", "Sustainability"],
    description: "Activities and awareness programs for World Environment Day",
    image: "/assets/spotlights/wed.webp",
    gallery: ["/assets/spotlights/wed.webp"],
  },
  {
    id: 20,
    date: "May 31, 2024",
    category: "education",
    title: "Campus Highlights",
    tags: ["Achievement", "Campus Life"],
    description:
      "Showcasing the latest highlights and achievements of the campus",
    image: "/assets/spotlights/ch.webp",
    gallery: ["/assets/spotlights/ch.webp"],
  },
  {
    id: 21,
    date: "May 29, 2024",
    category: "education",
    title: "Placement Highlights",
    tags: ["Career", "Success"],
    description:
      "Highlights from recent placement drives and student successes",
    image: "/assets/spotlights/ph.webp",
    gallery: ["/assets/spotlights/ph.webp"],
  },
  {
    id: 22,
    date: "May 27, 2024",
    category: "education",
    title: "Centre for Guidance and Career Development",
    tags: ["Career", "Guidance"],
    description: "Launch of the new Centre for Guidance and Career Development",
    image: "/assets/spotlights/cfgacd.webp",
    gallery: ["/assets/spotlights/cfgacd.webp"],
  },
  {
    id: 23,
    date: "May 13, 2024",
    category: "education",
    title: "Expert Session on National Technology Day",
    tags: ["Technology", "Innovation"],
    description:
      "An expert-led session discussing advancements on National Technology Day",
    image: "/assets/spotlights/esontd.webp",
    gallery: ["/assets/spotlights/esontd.webp"],
  },
  {
    id: 24,
    date: "May 12, 2024",
    category: "education",
    title: "Mother's Day",
    tags: ["Celebration", "Family"],
    description: "Celebrating Mother's Day with special events and honors",
    image: "/assets/spotlights/md.webp",
    gallery: ["/assets/spotlights/md.webp"],
  },
  {
    id: 25,
    date: "May 3, 2024",
    category: "education",
    title: "Coding Ninjas",
    tags: ["Technology", "Coding"],
    description:
      "Workshop on advanced coding techniques hosted by Coding Ninjas",
    image: "/assets/spotlights/cn.webp",
    gallery: ["/assets/spotlights/cn.webp"],
  },
  {
    id: 26,
    date: "May 1, 2024",
    category: "education",
    title: "IGCE & IGCMT Achievers",
    tags: ["Achievement", "Recognition"],
    description: "Recognizing the achievements of IGCE & IGCMT students",
    image: "/assets/spotlights/iia.webp",
    gallery: ["/assets/spotlights/iia.webp"],
  },
  {
    id: 27,
    date: "April 25, 2024",
    category: "education",
    title: "Expert Session on Eco-Consciousness",
    tags: ["Environment", "Sustainability"],
    description: "An expert-led session on promoting eco-consciousness",
    image: "/assets/spotlights/esoec.webp",
    gallery: ["/assets/spotlights/esoec.webp"],
  },
  {
    id: 28,
    date: "April 23, 2024",
    category: "education",
    title: "Session on Eco-Consciousness",
    tags: ["Environment", "Sustainability"],
    description: "Interactive session focusing on eco-conscious practices",
    image: "/assets/spotlights/esoec.webp",
    gallery: ["/assets/spotlights/esoec.webp"],
  },
  {
    id: 29,
    date: "April 23, 2024",
    category: "education",
    title: "IPL Fever Grips the Nation",
    tags: ["Sports", "Entertainment"],
    description: "Celebrating the excitement of IPL with various events",
    image: "/assets/spotlights/ifgtn.webp",
    gallery: ["/assets/spotlights/ifgtn.webp"],
  },
  {
    id: 30,
    date: "April 20, 2024",
    category: "education",
    title: "Campus Placement Drive",
    tags: ["Career", "Placement"],
    description: "Conducting a major placement drive for graduating students",
    image: "/assets/spotlights/cpd.webp",
    gallery: ["/assets/spotlights/cpd.webp"],
  },
];
