export const galleryData = [
  {
    id: 1,
    date: "2024-12-15",
    category: "events",
    image: "/assets/gallery/campus/Pic1.webp",
  },
  {
    id: 2,
    date: "2024-12-15",
    category: "events",
    image: "/assets/gallery/campus/pic2.webp",
  },
  {
    id: 3,
    date: "2024-12-15",
    category: "events",
    image: "/assets/gallery/campus/pic3.webp",
  },
  {
    id: 4,
    date: "2024-12-15",
    category: "events",
    image: "/assets/gallery/campus/pic4.webp",
  },
  {
    id: 5,
    date: "2024-12-15",
    category: "events",
    image: "/assets/gallery/campus/pic5.webp",
  },
  {
    id: 6,
    date: "2024-12-15",
    category: "events",
    image: "/assets/gallery/campus/pic6 all students.webp",
  },
  {
    id: 7,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/Aerial View.webp",
  },
  {
    id: 8,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IGCE Aerial view.webp",
  },
  {
    id: 9,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IGCE IGCMT Aerial View.webp",
  },
  {
    id: 10,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/Entrance Gate.webp",
  },
  {
    id: 11,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/Entrance1.webp",
  },
  {
    id: 12,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/Entrance1_11zon.webp",
  },
  {
    id: 13,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/Fountain Entrance.webp",
  },
  {
    id: 14,
    date: "2024-12-15",
    category: "infrastructure",
    image: "/assets/gallery/campus/boys hostel.webp",
  },
  {
    id: 15,
    date: "2024-12-15",
    category: "infrastructure",
    image: "/assets/gallery/campus/Girls Hostel.webp",
  },
  {
    id: 16,
    date: "2024-12-15",
    category: "infrastructure",
    image: "/assets/gallery/campus/Cafeteria.webp",
  },
  {
    id: 17,
    date: "2024-12-15",
    category: "infrastructure",
    image: "/assets/gallery/campus/IGCE Classroom.webp",
  },
  {
    id: 18,
    date: "2024-12-15",
    category: "infrastructure",
    image: "/assets/gallery/campus/Student Activity Centre.webp",
  },
  {
    id: 19,
    date: "2024-12-15",
    category: "infrastructure",
    image: "/assets/gallery/campus/Student Activity Centre2.webp",
  },
  {
    id: 20,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/Arch Lab.webp",
  },
  {
    id: 21,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/Arch Studio.webp",
  },
  {
    id: 22,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/Computer Lab 2.webp",
  },
  {
    id: 23,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/Computer Lab 4.webp",
  },
  {
    id: 24,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/FM Lab.webp",
  },
  {
    id: 25,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/FOSS LAB.webp",
  },
  {
    id: 26,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/IBM LAB2.webp",
  },
  {
    id: 27,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/Mech Lab.webp",
  },
  {
    id: 28,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/Mech Workshop.webp",
  },
  {
    id: 29,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/SOM.webp",
  },
  {
    id: 30,
    date: "2024-12-15",
    category: "labs",
    image: "/assets/gallery/campus/TOM Lab.webp",
  },
  {
    id: 31,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IMG20220509112747.webp",
  },
  {
    id: 32,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IMG20220509114236.webp",
  },
  {
    id: 33,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IMG20220509115308.webp",
  },
  {
    id: 34,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IMG20220509120330.webp",
  },
  {
    id: 35,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IMG20220509120404.webp",
  },
  {
    id: 36,
    date: "2024-12-15",
    category: "campus",
    image: "/assets/gallery/campus/IMG20220518110809.webp",
  },
];
